exclude: ^tests/llm_web_kit/extractor/html/magic_html/assets/

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [ "--max-line-length=2200", "--ignore=E131,E125,W503,W504,E203,E231,E702,E128,W604" ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: ["--style={based_on_style: google, column_limit: 200, indent_width: 4}"]
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.1
  #   hooks:
  #     - id: codespell
  #       exclude: '^tests/.*/assets/|llm_web_kit/model/assets/.*'
  #       args: ['--skip', '*.json']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: '^tests/.*/assets/|llm_web_kit/model/assets/.*'
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '^tests/.*/assets/|llm_web_kit/model/assets/.*'
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
        exclude: '^tests/.*/assets/|llm_web_kit/model/assets/.*'
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: [ "--remove" ]
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: [ "--number", "--table-width", "200" ]
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
        exclude: '^tests/.*/assets/|llm_web_kit/model/assets/.*'
